# SPDX-License-Identifier: GPL-3.0-or-later
"""Build `THIRD_PARTY_NOTICES` from the installed runtime distributions (docs/legal.md).

Every release must list each bundled package with its version, licence, copyright notice and
source URL. This collects what the installed metadata says; a human still reads it before a
release, because metadata is often incomplete.

Run it with: `uv run python tools/third_party_notices.py`
"""

import argparse
import importlib.metadata
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Final

# The packages the Windows build ships (docs/legal.md). Dev-only tools are not listed.
BUNDLED: Final = (
    "genieutils-py",
    "pywebview",
    "pillow",
    "pythonnet",
    "clr-loader",
    "cffi",
    "pycparser",
    "bottle",
    "proxy-tools",
    "typing-extensions",
)
# What the metadata never carries: files vendored by hand, and the runtime itself.
EXTRA: Final = """
## Bundled fonts

- **Barlow Semi Condensed** and **Marcellus SC** - SIL Open Font License 1.1.
  Copied from the google/fonts repository into `patch_scout/gui/web/vendor/fonts/`, each with
  its own `OFL.txt`.

## Bundled interface icons

- **Lucide** (https://lucide.dev) - ISC; the icons derived from Feather are MIT.
  Copied unedited into `patch_scout/gui/web/vendor/lucide/` with its `LICENSE` (D-43).

## Python

- **CPython** - Python Software Foundation License. The frozen runtime bundles CPython and its
  own third-party notices.

## Game content

Patch Scout ships **no game content**. Snapshots, icons and exports are made by the user from
their own install. Age of Empires II (C) Microsoft Corporation; see README.md for the notice
Microsoft's Game Content Usage Rules require.
"""

HEADER: Final = """# Third-party notices

Patch Scout is GPL-3.0-or-later. It bundles the packages below, each under its own licence.
Generated by `tools/third_party_notices.py` from the installed distributions, then reviewed by
hand before a release (docs/legal.md).
"""


# Packages whose metadata does not state a licence. Each was read from the project's own files
# and recorded in docs/legal.md; re-check when the pinned version changes.
KNOWN_LICENCES: Final = {
    "genieutils-py": "LGPL-3.0 (the LICENSE text is plain LGPLv3)",
    "clr-loader": "MIT",
}


def describe(name: str) -> str:
    """One package's entry, from whatever its metadata carries."""
    try:
        metadata = importlib.metadata.metadata(name)
    except importlib.metadata.PackageNotFoundError:
        return f"- **{name}** - not installed; check before releasing.\n"
    version = metadata.get("Version", "unknown")
    licence = (
        KNOWN_LICENCES.get(name)
        or metadata.get("License-Expression")
        or metadata.get("License")
        or "see the package"
    )
    if len(licence) > 80:  # some packages paste their whole licence text into the field
        licence = next(
            (
                value.removeprefix("License :: OSI Approved :: ")
                for value in metadata.get_all("Classifier") or []
                if value.startswith("License ::")
            ),
            "see the package's own licence file",
        )
    url = metadata.get("Home-page") or _project_url(metadata.get_all("Project-URL") or [])
    lines = [f"- **{name} {version}** - {licence.strip()}"]
    if url:
        lines.append(f"  Source: {url}")
    return "\n".join(lines) + "\n"


def _project_url(entries: Iterable[str]) -> str:
    for entry in entries:
        label, _, value = entry.partition(",")
        if label.strip().lower() in ("source", "repository", "homepage"):
            return value.strip()
    return ""


def render(packages: Sequence[str] = BUNDLED) -> str:
    """The whole file."""
    body = "".join(describe(name) for name in packages)
    return f"{HEADER}\n## Bundled Python packages\n\n{body}{EXTRA}"


def main(argv: Sequence[str] | None = None) -> int:
    """Write `THIRD_PARTY_NOTICES`, or check that it is up to date."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    parser.add_argument("--output", type=Path, default=Path("THIRD_PARTY_NOTICES"))
    arguments = parser.parse_args(argv)
    produced = render()
    if arguments.check:
        current = arguments.output.read_text(encoding="utf-8") if arguments.output.is_file() else ""
        if current != produced:
            return 1
        return 0
    arguments.output.write_text(produced, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
